# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: melonDS fuzzing harness example

BLOCKSDS ?= /opt/blocksds/core

# User config

NAME := hello_jit
GAME_TITLE := JIT Hello
GAME_SUBTITLE := melonDS fuzz

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
